delete from ARBITRO
delete from ENCONTRO
delete from FASE
delete from PARTICIPANTE
delete from PROVA
INSERT INTO ARBITRO (ID, NUM_FEDERATIVO) VALUES (1, 123)
INSERT INTO ARBITRO (ID, NUM_FEDERATIVO) VALUES (2, 234)
INSERT INTO ARBITRO (ID, NUM_FEDERATIVO) VALUES (3, 345)